<?php

namespace App\Support\Pdf;

use App\Models\Company;
use App\Models\InvoiceTemplate;
use App\Models\Setting;

/**
 * Renders a full-page preview of one InvoiceTemplate against a company's
 * real branding plus a fixed, realistic sample of line items — reused by
 * App\Http\Controllers\App\InvoiceTemplateController for both a saved
 * template's live-preview card and an uncreated preset's own preview card,
 * through the exact iframe-at-real-size-then-CSS-scale technique the OLD
 * single-preset gallery established (see the now-retired
 * SettingsController::invoiceTemplates()/invoice-templates.blade.php) —
 * just pointed at pdf.document-v2/pdf.payment-certificate-v2 instead of the
 * old pdf.document.
 *
 * $template need not be a persisted row: the gallery's preset cards build a
 * throwaway `new InvoiceTemplate(...)` from an InvoiceTemplatePresets entry
 * purely to reuse this renderer — nothing here ever saves or queries it.
 */
class InvoiceTemplatePreview
{
    public static function render(Company $company, string $documentType, string $lang, InvoiceTemplate $template): string
    {
        $view = $documentType === 'payment_certificate' ? 'pdf.payment-certificate-v2' : 'pdf.document-v2';
        $data = $documentType === 'payment_certificate'
            ? self::paymentCertificateData($company, $lang, $template)
            : self::documentData($company, $documentType, $lang, $template);

        $html = view($view, $data)->render();

        // pdf.document-v2/pdf.payment-certificate-v2's CSS relies on @page for
        // its page margins, which a browser only honors when actually
        // printing — on screen (this iframe preview) the body would
        // otherwise keep the browser's own default margin, throwing off a
        // layout whose head-band bleeds to the (print) page edge. Zeroing it
        // here only affects this on-screen preview, never a real PDF
        // download (identical fix to the old gallery's own technique).
        return str_replace('</head>', '<style>body{margin:0}</style></head>', $html);
    }

    /**
     * Sample data shaped exactly like InvoiceController::pdf() (and its
     * siblings) build for pdf.document-v2 — see that view's own docblock for
     * the full expected shape. A fixed, realistic construction-site line
     * item set stands in for a real document, same reasoning as the old
     * gallery's own sampleInvoicePreviewData().
     */
    private static function documentData(Company $company, string $documentType, string $lang, InvoiceTemplate $template): array
    {
        $items = [
            ['description' => $lang === 'ar' ? 'أعمال الحفر والموقع' : 'Excavation & sitework', 'qty' => 1, 'unit_price' => 12000, 'total' => 12000],
            ['description' => $lang === 'ar' ? 'توريد مواد البناء' : 'Construction materials supply', 'qty' => 4, 'unit_price' => 2500, 'total' => 10000],
            ['description' => $lang === 'ar' ? 'أجور العمالة' : 'Labor charges', 'qty' => 1, 'unit_price' => 6000, 'total' => 6000],
        ];
        $subtotal = (float) array_sum(array_column($items, 'total'));
        $vatRate = 15;
        $vatAmount = round($subtotal * $vatRate / 100, 2);

        return [
            'lang' => $lang,
            'currency' => 'SAR',
            'docType' => $documentType,
            'docNumber' => 'SAMPLE-0001',
            'docDate' => now(),
            'validUntil' => now()->addDays(30),
            'status' => $lang === 'ar' ? 'مسودة' : 'Draft',
            'issuer' => [
                'name' => $company->name ?: ($lang === 'ar' ? 'اسم الشركة' : 'Your Company'),
                'meta' => array_filter([$company->phone ?? null, ($company->vat_number ?? null) ? 'VAT: ' . $company->vat_number : null, ($company->cr_number ?? null) ? 'CR: ' . $company->cr_number : null]),
            ],
            'companyNameAr' => $company->name_ar ?? '',
            'companyLogo' => !empty($company->logo_path) ? ('file://' . public_path($company->logo_path)) : null,
            'billTo' => ['name' => $lang === 'ar' ? 'شركة نموذجية للمقاولات' : 'Sample Client Co.', 'meta' => [$lang === 'ar' ? 'الرياض، المملكة العربية السعودية' : 'Riyadh, Saudi Arabia']],
            'items' => $items,
            'subtotal' => $subtotal,
            'discountPercent' => 0,
            'discountAmount' => 0,
            'vatRate' => $vatRate,
            'vatAmount' => $vatAmount,
            'total' => $subtotal + $vatAmount,
            'qrCode' => null,
            'footerNote' => $lang === 'ar' ? 'تم إنشاؤه بواسطة ' . Setting::siteName() : 'Generated by ' . Setting::siteName(),
            'invoiceTemplate' => $template,
            'company' => $company,
            'documentType' => $documentType,
            'pageSize' => $template->page_size ?: 'a4',
            'partyLabelKey' => $documentType === 'purchase_order' ? 'pdf.supplier' : 'pdf.bill_to',
            'partyNameAr' => 'شركة نموذجية للمقاولات',
            'partyVat' => '300012345600003',
            'zatcaStatus' => null,
            'notes' => null,
        ];
    }

    /**
     * Sample data shaped like PaymentCertificateController::pdf() builds for
     * pdf.payment-certificate-v2 — plain unsaved stdClass objects, since
     * that view only ever reads their attributes and never calls a
     * relation/query method on them (unlike Project::boqContractValue(),
     * which the controller itself resolves into the plain 'contractValue'
     * number before the view ever sees it).
     */
    private static function paymentCertificateData(Company $company, string $lang, InvoiceTemplate $template): array
    {
        $project = (object) ['name' => 'Sample Villa Project', 'name_ar' => 'مشروع فيلا نموذجي'];
        $client = (object) ['name' => 'Sample Client Co.', 'name_ar' => 'شركة نموذجية للمقاولات'];
        $certificate = (object) [
            'certificate_number' => 'IPC-01',
            'status' => 'draft',
            'certificate_date' => now()->toDateString(),
            'cumulative_certified' => 45000,
            'gross_amount' => 45000,
            'retention_percent' => 5,
            'retention_amount' => 2250,
            'advance_recovery_amount' => 0,
            'net_payable' => 42750,
            'notes' => null,
        ];
        $lines = [
            (object) ['description' => 'Concrete works', 'uom' => 'm3', 'contract_qty' => 200, 'contract_unit_price' => 300, 'previous_cumulative_qty' => 100, 'cumulative_qty' => 150, 'this_period_qty' => 50, 'this_period_value' => 15000],
            (object) ['description' => 'Steel reinforcement', 'uom' => 'ton', 'contract_qty' => 40, 'contract_unit_price' => 750, 'previous_cumulative_qty' => 20, 'cumulative_qty' => 40, 'this_period_qty' => 20, 'this_period_value' => 15000],
        ];
        $contractValue = 200000;
        $vatRate = 15;
        $vatAmount = round(42750 * $vatRate / 100, 2);

        return [
            'lang' => $lang,
            'currency' => 'SAR',
            'company' => $company,
            'project' => $project,
            'client' => $client,
            'certificate' => $certificate,
            'lines' => $lines,
            'contractValue' => $contractValue,
            'vatRate' => $vatRate,
            'vatAmount' => $vatAmount,
            'totalDue' => 42750 + $vatAmount,
            'invoiceTemplate' => $template,
        ];
    }
}
